### ISSUE TITLE
onlymeith.ogg is receiving copyright claims on youtube

### ISSUE THREAD

**Issue by TheGoddessInari** [sayterdarkwynd/FrackinMusic#6]
`onlymeith DFA ft DJ Vadim, Geert Veneklaas` is receiving claims from `BPM Media Inc. Publishing, Dart Music Inc`.

FrackinMusic claims to use only copyright-free/royalty-free sources, but this song according to [the archived ccmixer page](https://web.archive.org/web/20181206191256/https://ccmixter.org/files/onlymeith/53446) is copyrighted and licensed with CC noncommercial, which is different and subject to copyright claims.

**Comment by sayterdarkwynd** [comment]
thanks. ill get it swapped out
